/**
 * Push CockroachDB schema using the runtime SSL pool (rejectUnauthorized: false).
 * Uses explicit INT4 sequences to avoid CockroachDB's unique_rowid() 64-bit IDs.
 * Run with: pnpm --filter @workspace/db exec tsx src/push-cockroach.ts
 */
import pg from "pg";

const { Pool } = pg;

const url = process.env.COCKROACH_DATABASE_URL;
if (!url) throw new Error("COCKROACH_DATABASE_URL must be set");

const pool = new Pool({
  connectionString: url,
  ssl: { rejectUnauthorized: false },
});

// Using INT4 GENERATED BY DEFAULT AS IDENTITY avoids CockroachDB's unique_rowid()
// which produces 64-bit values that exceed JS's safe integer range.
const DDL_STATEMENTS = [
  // Sequences for each table
  `CREATE SEQUENCE IF NOT EXISTS products_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS inventory_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS production_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS sales_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS sale_items_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS deliveries_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS expenses_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS wholesale_customers_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS wholesale_supplies_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS wholesale_supply_items_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS attendance_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS salary_payments_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS notifications_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS pending_approvals_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS inventory_adjustments_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS shop_receipts_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS daily_counts_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS conversations_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS messages_id_seq AS INT`,
  `CREATE SEQUENCE IF NOT EXISTS shift_closings_id_seq AS INT`,

  // Tables using nextval() to get regular INT IDs
  `CREATE TABLE IF NOT EXISTS products (
    id INT PRIMARY KEY DEFAULT nextval('products_id_seq'),
    name TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT 'piece',
    category TEXT,
    low_stock_threshold INT NOT NULL DEFAULT 10,
    is_active BOOL NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS inventory (
    id INT PRIMARY KEY DEFAULT nextval('inventory_id_seq'),
    product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    current_stock INT NOT NULL DEFAULT 0,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (product_id)
  )`,

  `CREATE TABLE IF NOT EXISTS production (
    id INT PRIMARY KEY DEFAULT nextval('production_id_seq'),
    product_id INT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL,
    notes TEXT,
    produced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS sales (
    id INT PRIMARY KEY DEFAULT nextval('sales_id_seq'),
    cashier_id INT,
    payment_method TEXT NOT NULL DEFAULT 'cash',
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    sold_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS sale_items (
    id INT PRIMARY KEY DEFAULT nextval('sale_items_id_seq'),
    sale_id INT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS deliveries (
    id INT PRIMARY KEY DEFAULT nextval('deliveries_id_seq'),
    order_id INT NOT NULL,
    rider_id INT,
    status TEXT NOT NULL DEFAULT 'assigned',
    pickup_time TIMESTAMPTZ,
    delivery_time TIMESTAMPTZ,
    delivery_fee NUMERIC(10,2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS expenses (
    id INT PRIMARY KEY DEFAULT nextval('expenses_id_seq'),
    description TEXT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    category TEXT NOT NULL DEFAULT 'general',
    expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
    recorded_by INT,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS wholesale_customers (
    id INT PRIMARY KEY DEFAULT nextval('wholesale_customers_id_seq'),
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    credit_limit NUMERIC(12,2) NOT NULL DEFAULT 0,
    outstanding_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
    is_active BOOL NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS wholesale_supplies (
    id INT PRIMARY KEY DEFAULT nextval('wholesale_supplies_id_seq'),
    customer_id INT NOT NULL REFERENCES wholesale_customers(id),
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    amount_paid NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_status TEXT NOT NULL DEFAULT 'unpaid',
    supplied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT
  )`,

  `CREATE TABLE IF NOT EXISTS wholesale_supply_items (
    id INT PRIMARY KEY DEFAULT nextval('wholesale_supply_items_id_seq'),
    supply_id INT NOT NULL REFERENCES wholesale_supplies(id) ON DELETE CASCADE,
    product_id INT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL
  )`,

  `CREATE TABLE IF NOT EXISTS attendance (
    id INT PRIMARY KEY DEFAULT nextval('attendance_id_seq'),
    employee_id INT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ,
    check_out TIMESTAMPTZ,
    hours_worked NUMERIC(5,2),
    notes TEXT,
    UNIQUE (employee_id, date)
  )`,

  `CREATE TABLE IF NOT EXISTS salary_payments (
    id INT PRIMARY KEY DEFAULT nextval('salary_payments_id_seq'),
    employee_id INT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    period TEXT NOT NULL,
    payment_method TEXT NOT NULL DEFAULT 'cash',
    notes TEXT,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS notifications (
    id INT PRIMARY KEY DEFAULT nextval('notifications_id_seq'),
    user_id INT NOT NULL,
    type TEXT NOT NULL DEFAULT 'info',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOL NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS pending_approvals (
    id INT PRIMARY KEY DEFAULT nextval('pending_approvals_id_seq'),
    action_type TEXT NOT NULL,
    target_user_id INT NOT NULL,
    target_user_name TEXT NOT NULL,
    target_username TEXT NOT NULL,
    requested_by_id INT NOT NULL,
    requested_by_name TEXT NOT NULL,
    new_password TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    reviewer_notes TEXT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS inventory_adjustments (
    id INT PRIMARY KEY DEFAULT nextval('inventory_adjustments_id_seq'),
    product_id INT NOT NULL REFERENCES products(id),
    adjustment INT NOT NULL,
    reason TEXT,
    adjusted_by INT,
    adjusted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS shop_receipts (
    id INT PRIMARY KEY DEFAULT nextval('shop_receipts_id_seq'),
    shift_date DATE NOT NULL,
    product_id INT NOT NULL REFERENCES products(id),
    opening_count INT NOT NULL DEFAULT 0,
    closing_count INT NOT NULL DEFAULT 0,
    sold_count INT NOT NULL DEFAULT 0,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    total_sales NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS daily_counts (
    id INT PRIMARY KEY DEFAULT nextval('daily_counts_id_seq'),
    product_id INT NOT NULL REFERENCES products(id),
    count_type TEXT NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    count_date DATE NOT NULL DEFAULT CURRENT_DATE,
    counted_by INT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS conversations (
    id INT PRIMARY KEY DEFAULT nextval('conversations_id_seq'),
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS messages (
    id INT PRIMARY KEY DEFAULT nextval('messages_id_seq'),
    conversation_id INT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,

  `CREATE TABLE IF NOT EXISTS shift_closings (
    id INT PRIMARY KEY DEFAULT nextval('shift_closings_id_seq'),
    closed_by TEXT NOT NULL,
    shift_date DATE NOT NULL UNIQUE,
    closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'approved',
    approved_by TEXT,
    approved_at TIMESTAMPTZ
  )`,
];

async function main() {
  const client = await pool.connect();
  try {
    const vRes = await client.query("SELECT version()");
    console.log("Connected:", vRes.rows[0].version.split(" ").slice(0, 3).join(" "));

    // Drop and recreate — only safe on a fresh/empty DB
    const tableNames = [
      "messages", "conversations", "shift_closings", "daily_counts", "shop_receipts",
      "inventory_adjustments", "pending_approvals", "notifications", "salary_payments",
      "attendance", "wholesale_supply_items", "wholesale_supplies", "wholesale_customers",
      "expenses", "deliveries", "sale_items", "sales", "production", "inventory", "products",
    ];
    console.log("Dropping existing tables...");
    for (const t of tableNames) {
      await client.query(`DROP TABLE IF EXISTS ${t} CASCADE`).catch(() => {});
    }
    const seqNames = [
      "products_id_seq", "inventory_id_seq", "production_id_seq", "sales_id_seq",
      "sale_items_id_seq", "deliveries_id_seq", "expenses_id_seq",
      "wholesale_customers_id_seq", "wholesale_supplies_id_seq", "wholesale_supply_items_id_seq",
      "attendance_id_seq", "salary_payments_id_seq", "notifications_id_seq",
      "pending_approvals_id_seq", "inventory_adjustments_id_seq", "shop_receipts_id_seq",
      "daily_counts_id_seq", "conversations_id_seq", "messages_id_seq", "shift_closings_id_seq",
    ];
    for (const s of seqNames) {
      await client.query(`DROP SEQUENCE IF EXISTS ${s} CASCADE`).catch(() => {});
    }

    let ok = 0;
    for (const stmt of DDL_STATEMENTS) {
      try {
        await client.query(stmt);
        ok++;
      } catch (e: any) {
        console.error("Failed:", stmt.slice(0, 80), "\n  →", e.message);
      }
    }
    console.log(`Done — ${ok}/${DDL_STATEMENTS.length} statements executed.`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
